version: "3.8"

services:
  frontend:
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    # Due to stupid react-scripts bug still present in v3.4.3
    # https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true

  backend:
    build:
      dockerfile: ./Dockerfile.dev  
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/usr/src/backend
      - speedtest_backend_node_volumes:/usr/src/backend/node_modules

volumes:
  speedtest_backend_node_volumes:
